#include "DwtDsp.h"

#include <unordered_map>

namespace dsp
{

std::string WavelettoString(MotherWavelet wavelet)
{
    static const std::unordered_map<MotherWavelet, std::string> map
    {
        std::make_pair(MotherWavelet::Haar, "haar"),
        std::make_pair(MotherWavelet::Daubechies1, "db1"),
        std::make_pair(MotherWavelet::Daubechies2, "db2"),
        std::make_pair(MotherWavelet::Daubechies3, "db3"),
        std::make_pair(MotherWavelet::Daubechies4, "db4"),
        std::make_pair(MotherWavelet::Daubechies5, "db5"),
        std::make_pair(MotherWavelet::Daubechies6, "db6"),
        std::make_pair(MotherWavelet::Daubechies7, "db7"),
        std::make_pair(MotherWavelet::Daubechies8, "db8"),
        std::make_pair(MotherWavelet::Daubechies9, "db9"),
        std::make_pair(MotherWavelet::Daubechies10, "db10"),
        std::make_pair(MotherWavelet::Daubechies11, "db11"),
        std::make_pair(MotherWavelet::Daubechies12, "db12"),
        std::make_pair(MotherWavelet::Daubechies13, "db13"),
        std::make_pair(MotherWavelet::Daubechies14, "db14"),
        std::make_pair(MotherWavelet::Daubechies15, "db15"),
        std::make_pair(MotherWavelet::Daubechies16, "db16"),
        std::make_pair(MotherWavelet::Daubechies17, "db17"),
        std::make_pair(MotherWavelet::Daubechies18, "db18"),
        std::make_pair(MotherWavelet::Daubechies19, "db19"),
        std::make_pair(MotherWavelet::Daubechies20, "db20"),
        std::make_pair(MotherWavelet::Daubechies21, "db21"),
        std::make_pair(MotherWavelet::Daubechies22, "db22"),
        std::make_pair(MotherWavelet::Daubechies23, "db23"),
        std::make_pair(MotherWavelet::Daubechies24, "db24"),
        std::make_pair(MotherWavelet::Daubechies25, "db25"),
        std::make_pair(MotherWavelet::Daubechies26, "db26"),
        std::make_pair(MotherWavelet::Daubechies27, "db27"),
        std::make_pair(MotherWavelet::Daubechies28, "db28"),
        std::make_pair(MotherWavelet::Daubechies29, "db29"),
        std::make_pair(MotherWavelet::Daubechies30, "db30"),
        std::make_pair(MotherWavelet::Daubechies31, "db31"),
        std::make_pair(MotherWavelet::Daubechies32, "db32"),
        std::make_pair(MotherWavelet::Daubechies33, "db33"),
        std::make_pair(MotherWavelet::Daubechies34, "db34"),
        std::make_pair(MotherWavelet::Daubechies35, "db35"),
        std::make_pair(MotherWavelet::Daubechies36, "db36"),
        std::make_pair(MotherWavelet::Daubechies37, "db37"),
        std::make_pair(MotherWavelet::Daubechies38, "db38"),
        std::make_pair(MotherWavelet::Bior1_1, "bior1.1"),
        std::make_pair(MotherWavelet::Bior1_3, "bior1.3"),
        std::make_pair(MotherWavelet::Bior1_5, "bior1.5"),
        std::make_pair(MotherWavelet::Bior2_2, "bior2.2"),
        std::make_pair(MotherWavelet::Bior2_4, "bior2.4"),
        std::make_pair(MotherWavelet::Bior2_6, "bior2.6"),
        std::make_pair(MotherWavelet::Bior2_8, "bior2.8"),
        std::make_pair(MotherWavelet::Bior3_1, "bior3.1"),
        std::make_pair(MotherWavelet::Bior3_3, "bior3.3"),
        std::make_pair(MotherWavelet::Bior3_5, "bior3.5"),
        std::make_pair(MotherWavelet::Bior3_7, "bior3.7"),
        std::make_pair(MotherWavelet::Bior3_9, "bior3.9"),
        std::make_pair(MotherWavelet::Bior4_4, "bior4.4"),
        std::make_pair(MotherWavelet::Bior5_5, "bior5.5"),
        std::make_pair(MotherWavelet::Bior6_8, "bior6.8"),
        std::make_pair(MotherWavelet::RBior1_1, "rbior1.1"),
        std::make_pair(MotherWavelet::RBior1_3, "rbior1.3"),
        std::make_pair(MotherWavelet::RBior1_5, "rbior1.5"),
        std::make_pair(MotherWavelet::RBior2_2, "rbior2.2"),
        std::make_pair(MotherWavelet::RBior2_4, "rbior2.4"),
        std::make_pair(MotherWavelet::RBior2_6, "rbior2.6"),
        std::make_pair(MotherWavelet::RBior2_8, "rbior2.8"),
        std::make_pair(MotherWavelet::RBior3_1, "rbior3.1"),
        std::make_pair(MotherWavelet::RBior3_3, "rbior3.3"),
        std::make_pair(MotherWavelet::RBior3_5, "rbior3.5"),
        std::make_pair(MotherWavelet::RBior3_7, "rbior3.7"),
        std::make_pair(MotherWavelet::RBior3_9, "rbior3.9"),
        std::make_pair(MotherWavelet::RBior4_4, "rbior4.4"),
        std::make_pair(MotherWavelet::RBior5_5, "rbior5.5"),
        std::make_pair(MotherWavelet::RBior6_8, "rbior6.8"),
        std::make_pair(MotherWavelet::Coiflet1, "coif1"),
        std::make_pair(MotherWavelet::Coiflet2, "coif2"),
        std::make_pair(MotherWavelet::Coiflet3, "coif3"),
        std::make_pair(MotherWavelet::Coiflet4, "coif4"),
        std::make_pair(MotherWavelet::Coiflet5, "coif5"),
        std::make_pair(MotherWavelet::Coiflet6, "coif6"),
        std::make_pair(MotherWavelet::Coiflet7, "coif7"),
        std::make_pair(MotherWavelet::Coiflet8, "coif8"),
        std::make_pair(MotherWavelet::Coiflet9, "coif9"),
        std::make_pair(MotherWavelet::Coiflet10, "coif10"),
        std::make_pair(MotherWavelet::Coiflet11, "coif11"),
        std::make_pair(MotherWavelet::Coiflet12, "coif12"),
        std::make_pair(MotherWavelet::Coiflet13, "coif13"),
        std::make_pair(MotherWavelet::Coiflet14, "coif14"),
        std::make_pair(MotherWavelet::Coiflet15, "coif15"),
        std::make_pair(MotherWavelet::Coiflet16, "coif16"),
        std::make_pair(MotherWavelet::Symmlet2, "sym2"),
        std::make_pair(MotherWavelet::Symmlet3, "sym3"),
        std::make_pair(MotherWavelet::Symmlet4, "sym4"),
        std::make_pair(MotherWavelet::Symmlet5, "sym5"),
        std::make_pair(MotherWavelet::Symmlet6, "sym6"),
        std::make_pair(MotherWavelet::Symmlet7, "sym7"),
        std::make_pair(MotherWavelet::Symmlet8, "sym8"),
        std::make_pair(MotherWavelet::Symmlet9, "sym9"),
        std::make_pair(MotherWavelet::Symmlet10, "sym10"),
        std::make_pair(MotherWavelet::Symmlet11, "sym11"),
        std::make_pair(MotherWavelet::Symmlet12, "sym12"),
        std::make_pair(MotherWavelet::Symmlet13, "sym13"),
        std::make_pair(MotherWavelet::Symmlet14, "sym14"),
        std::make_pair(MotherWavelet::Symmlet15, "sym15"),
        std::make_pair(MotherWavelet::Symmlet16, "sym16"),
        std::make_pair(MotherWavelet::Symmlet17, "sym17"),
        std::make_pair(MotherWavelet::Symmlet18, "sym18"),
        std::make_pair(MotherWavelet::Symmlet19, "sym19"),
        std::make_pair(MotherWavelet::Symmlet20, "sym20")
    };

    return map.at(wavelet);
}

MotherWavelet StringtoWavelet(const std::string& wavelet)
{
    static const std::unordered_map<std::string, MotherWavelet> map
    {
        std::make_pair("haar", MotherWavelet::Haar),
        std::make_pair("db1", MotherWavelet::Daubechies1),
        std::make_pair("db2", MotherWavelet::Daubechies2),
        std::make_pair("db3", MotherWavelet::Daubechies3),
        std::make_pair("db4", MotherWavelet::Daubechies4),
        std::make_pair("db5", MotherWavelet::Daubechies5),
        std::make_pair("db6", MotherWavelet::Daubechies6),
        std::make_pair("db7", MotherWavelet::Daubechies7),
        std::make_pair("db8", MotherWavelet::Daubechies8),
        std::make_pair("db9", MotherWavelet::Daubechies9),
        std::make_pair("db10", MotherWavelet::Daubechies10),
        std::make_pair("db11", MotherWavelet::Daubechies11),
        std::make_pair("db12", MotherWavelet::Daubechies12),
        std::make_pair("db13", MotherWavelet::Daubechies13),
        std::make_pair("db14", MotherWavelet::Daubechies14),
        std::make_pair("db15", MotherWavelet::Daubechies15),
        std::make_pair("db16", MotherWavelet::Daubechies16),
        std::make_pair("db17", MotherWavelet::Daubechies17),
        std::make_pair("db18", MotherWavelet::Daubechies18),
        std::make_pair("db19", MotherWavelet::Daubechies19),
        std::make_pair("db20", MotherWavelet::Daubechies20),
        std::make_pair("db21", MotherWavelet::Daubechies21),
        std::make_pair("db22", MotherWavelet::Daubechies22),
        std::make_pair("db23", MotherWavelet::Daubechies23),
        std::make_pair("db24", MotherWavelet::Daubechies24),
        std::make_pair("db25", MotherWavelet::Daubechies25),
        std::make_pair("db26", MotherWavelet::Daubechies26),
        std::make_pair("db27", MotherWavelet::Daubechies27),
        std::make_pair("db28", MotherWavelet::Daubechies28),
        std::make_pair("db29", MotherWavelet::Daubechies29),
        std::make_pair("db30", MotherWavelet::Daubechies30),
        std::make_pair("db31", MotherWavelet::Daubechies31),
        std::make_pair("db32", MotherWavelet::Daubechies32),
        std::make_pair("db33", MotherWavelet::Daubechies33),
        std::make_pair("db34", MotherWavelet::Daubechies34),
        std::make_pair("db35", MotherWavelet::Daubechies35),
        std::make_pair("db36", MotherWavelet::Daubechies36),
        std::make_pair("db37", MotherWavelet::Daubechies37),
        std::make_pair("db38", MotherWavelet::Daubechies38),
        std::make_pair("bior1.1", MotherWavelet::Bior1_1),
        std::make_pair("bior1.3", MotherWavelet::Bior1_3),
        std::make_pair("bior1.5", MotherWavelet::Bior1_5),
        std::make_pair("bior2.2", MotherWavelet::Bior2_2),
        std::make_pair("bior2.4", MotherWavelet::Bior2_4),
        std::make_pair("bior2.6", MotherWavelet::Bior2_6),
        std::make_pair("bior2.8", MotherWavelet::Bior2_8),
        std::make_pair("bior3.1", MotherWavelet::Bior3_1),
        std::make_pair("bior3.3", MotherWavelet::Bior3_3),
        std::make_pair("bior3.5", MotherWavelet::Bior3_5),
        std::make_pair("bior3.7", MotherWavelet::Bior3_7),
        std::make_pair("bior3.9", MotherWavelet::Bior3_9),
        std::make_pair("bior4.4", MotherWavelet::Bior4_4),
        std::make_pair("bior5.5", MotherWavelet::Bior5_5),
        std::make_pair("bior6.8", MotherWavelet::Bior6_8),
        std::make_pair("rbior1.1", MotherWavelet::RBior1_1),
        std::make_pair("rbior1.3", MotherWavelet::RBior1_3),
        std::make_pair("rbior1.5", MotherWavelet::RBior1_5),
        std::make_pair("rbior2.2", MotherWavelet::RBior2_2),
        std::make_pair("rbior2.4", MotherWavelet::RBior2_4),
        std::make_pair("rbior2.6", MotherWavelet::RBior2_6),
        std::make_pair("rbior2.8", MotherWavelet::RBior2_8),
        std::make_pair("rbior3.1", MotherWavelet::RBior3_1),
        std::make_pair("rbior3.3", MotherWavelet::RBior3_3),
        std::make_pair("rbior3.5", MotherWavelet::RBior3_5),
        std::make_pair("rbior3.7", MotherWavelet::RBior3_7),
        std::make_pair("rbior3.9", MotherWavelet::RBior3_9),
        std::make_pair("rbior4.4", MotherWavelet::RBior4_4),
        std::make_pair("rbior5.5", MotherWavelet::RBior5_5),
        std::make_pair("rbior6.8", MotherWavelet::RBior6_8),
        std::make_pair("coif1", MotherWavelet::Coiflet1),
        std::make_pair("coif2", MotherWavelet::Coiflet2),
        std::make_pair("coif3", MotherWavelet::Coiflet3),
        std::make_pair("coif4", MotherWavelet::Coiflet4),
        std::make_pair("coif5", MotherWavelet::Coiflet5),
        std::make_pair("coif6", MotherWavelet::Coiflet6),
        std::make_pair("coif7", MotherWavelet::Coiflet7),
        std::make_pair("coif8", MotherWavelet::Coiflet8),
        std::make_pair("coif9", MotherWavelet::Coiflet9),
        std::make_pair("coif10", MotherWavelet::Coiflet10),
        std::make_pair("coif11", MotherWavelet::Coiflet11),
        std::make_pair("coif12", MotherWavelet::Coiflet12),
        std::make_pair("coif13", MotherWavelet::Coiflet13),
        std::make_pair("coif14", MotherWavelet::Coiflet14),
        std::make_pair("coif15", MotherWavelet::Coiflet15),
        std::make_pair("coif16", MotherWavelet::Coiflet16),
        std::make_pair("sym2", MotherWavelet::Symmlet2),
        std::make_pair("sym3", MotherWavelet::Symmlet3),
        std::make_pair("sym4", MotherWavelet::Symmlet4),
        std::make_pair("sym5", MotherWavelet::Symmlet5),
        std::make_pair("sym6", MotherWavelet::Symmlet6),
        std::make_pair("sym7", MotherWavelet::Symmlet7),
        std::make_pair("sym8", MotherWavelet::Symmlet8),
        std::make_pair("sym9", MotherWavelet::Symmlet9),
        std::make_pair("sym10", MotherWavelet::Symmlet10),
        std::make_pair("sym11", MotherWavelet::Symmlet11),
        std::make_pair("sym12", MotherWavelet::Symmlet12),
        std::make_pair("sym13", MotherWavelet::Symmlet13),
        std::make_pair("sym14", MotherWavelet::Symmlet14),
        std::make_pair("sym15", MotherWavelet::Symmlet15),
        std::make_pair("sym16", MotherWavelet::Symmlet16),
        std::make_pair("sym17", MotherWavelet::Symmlet17),
        std::make_pair("sym18", MotherWavelet::Symmlet18),
        std::make_pair("sym19", MotherWavelet::Symmlet19),
        std::make_pair("sym20", MotherWavelet::Symmlet20)
    };

    if (map.find(wavelet) != map.cend())
        return map.at(wavelet);
    else
        return map.at(WavelettoString(MotherWavelet::Haar));
}

}
